let shopItemsdata = [
  {
    id: "jhpfgigcnkdfpnk",
    name: "Nike Air White Edition",
    price: 140,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    Image: "img/sneakers1.jpg",
    amount: 1,
  },
  {
    id: "kpoypongpokmlklk",
    name: "AF-1",
    price: 160,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    Image: "img/sneakers.jpg",
    amount: 1,
  },
  {
    id: "kjkjgpkfopknn",
    name: "YEEZY",
    price: 189,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    Image: "img/sneaker2.jpg",
    amount: 1,
  },
  {
    id: "pkpogkpoknpgnk",
    name: "Air-Jordan BR Edition",
    price: 120,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    Image: "img/sneakers3.jpg",
    amount: 1,
  },
  {
    id: "pokhpgocpoknfpkn",
    name: "BALANCIAGA",
    price: 250,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    Image: "img/sneakers4.jpg",
    amount: 1,
  },
  {
    id: "pkjponkopfknpkk",
    name: "Air-Jordan RW Edition",
    price: 179,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    Image: "img/sneakers5.jpg",
    amount: 1,
  },
  {
    id: "pkogfpnokfpnkpoknpfkh",
    name: "Vans Walk OFF walls",
    price: 129,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    Image: "img/sneakers6.jpg",
    amount: 1,
  },
  {
    id: "opfknpofpnkpofkpnk",
    name: "Nike Free",
    price: 149,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    Image: "img/nike shoe.jpg",
    amount: 1,
  },
];
